# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci --omit=dev

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65182236E2F14DB7B28C98E33BD7C7FD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5817DF4913E543EFB495EAC7E8DAAE24 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98ECDC6483044AF88D2A281DC8C5AFC3 }}

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Dorm-FiX'
          slot-name: 'Production'
          package: ./backend
